name: Pipeline failure
description: Build Fluorite / Test Fluorite workflow failed unexpectedly
labels: ['ci']
body:
  - type: dropdown
    id: stage
    attributes:
      label: Failing stage
      options:
        - images (GHCR build/push)
        - build (ninja/gn)
        - test static
        - test emulator
        - release
        - other
    validations:
      required: true
  - type: input
    id: run
    attributes:
      label: Link to failed run
    validations:
      required: true
  - type: textarea
    id: log
    attributes:
      label: Relevant log excerpt
      render: shell
